/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import org.omg.CORBA.NO_IMPLEMENT;
import sinvent.ConexionSQL;
import sinvent.IncAuto;

/**
 *
 * @author hp
 */
public class N_compra extends javax.swing.JFrame {

    /**
     * Creates new form N_compra
     */ ConexionSQL cc= new ConexionSQL();
        Connection con = cc.conexion();
        IncAuto au= new IncAuto();
        
        
    public N_compra() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id_producto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id_proveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        Comentario = new javax.swing.JTextField();
        Verificar = new javax.swing.JButton();
        Comprar = new javax.swing.JButton();
        No_compra = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        texto2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 450));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel1.setText("ID Producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 26));

        id_producto.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, 26));

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 26));

        Cantidad.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 211, 26));

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel3.setText("ID Proveedor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 25));

        id_proveedor.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(id_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 212, 25));

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel4.setText("Precio a pagar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 30));

        Precio.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 70, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("$");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 20, -1));

        texto.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        texto.setText("Comentario:");
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, 30));

        Comentario.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(Comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 250, 60));

        Verificar.setBackground(new java.awt.Color(0, 255, 51));
        Verificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/verificar.png"))); // NOI18N
        Verificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                VerificarActionPerformed(evt);
            }
        });
        getContentPane().add(Verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 70, 70));

        Comprar.setBackground(new java.awt.Color(0, 153, 255));
        Comprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/comprar.png"))); // NOI18N
        Comprar.setEnabled(false);
        Comprar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ComprarActionPerformed(evt);
            }
        });
        getContentPane().add(Comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 70, 70));

        No_compra.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        No_compra.addAncestorListener(new javax.swing.event.AncestorListener()
        {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt)
            {
                No_compraAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt)
            {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt)
            {
            }
        });
        getContentPane().add(No_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 110, 28));

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel7.setText("Compra Actual N°:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 28));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/Exit.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 32, 28));

        texto2.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        texto2.setText("Verificar");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 70, 30));

        texto1.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        texto1.setText("Comprar");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 70, 30));

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel8.setText("Nueva Compra");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 440, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void No_compraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_No_compraAncestorAdded
        /*esta accion sirve para mostrar al usuario el numero de venta que se está llevando
        principalmente para saber el ID de la Compra en curso*/
        
        No_compra.setText(String.valueOf(au.autoincCompras()));
    }//GEN-LAST:event_No_compraAncestorAdded

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
            AgregarCompra();
    }//GEN-LAST:event_ComprarActionPerformed

    private void VerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarActionPerformed
        Validar();
    }//GEN-LAST:event_VerificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OpcionesCompra a= new OpcionesCompra();
        a.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void AgregarCompra (){
        /*esta operacion guarda los datos de los campos en el Jframe a la base de datos*/
        String SQL = "insert into ncompras(id_compra,id_producto,cantidad,id_proveedor,precio,comentario) values(?,?,?,?,?,?)";
        try {
             PreparedStatement pst = con.prepareStatement(SQL);
             
             pst.setString(1, String.valueOf(au.autoincCompras()));
             pst.setString(2, id_producto.getText());
              pst.setString(3, Cantidad.getText());
               pst.setString(4, id_proveedor.getText());
                pst.setString(5, Precio.getText());
                 pst.setString(6, Comentario.getText());
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(null, "registro exisoto");
                  OpcionesCompra a= new OpcionesCompra();
                  a.setVisible(true);
                  
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog( null,"Error al Guardar"+e.getMessage());
        }
       
        
        
        
    }
    public void Validar(){
        /*esta operacion valida cada uno de los campos para que ningun campo se guarde vacio en 
        la base de datos*/
        
        if(!id_producto.getText().isEmpty()){
            if(!Cantidad.getText().isEmpty()){
                if(!id_proveedor.getText().isEmpty()){
                    if(!Precio.getText().isEmpty()){
                        if(!Comentario.getText().isEmpty()){
                            Comprar.setEnabled(true);
                        }else{
                            JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           Comprar.setEnabled(false); 
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           Comprar.setEnabled(false); 
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           Comprar.setEnabled(false); 
                }
            }else{
                JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           Comprar.setEnabled(false); 
            }
        }else{
             JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           Comprar.setEnabled(false); 
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_compra().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cantidad;
    private javax.swing.JTextField Comentario;
    private javax.swing.JButton Comprar;
    private javax.swing.JLabel No_compra;
    private javax.swing.JTextField Precio;
    private javax.swing.JButton Verificar;
    private javax.swing.JTextField id_producto;
    private javax.swing.JTextField id_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables


}

