/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import org.omg.CORBA.NO_IMPLEMENT;
import sinvent.ConexionSQL;
import sinvent.IncAuto;

/**
 *
 * @author hp
 */
public class N_producto extends javax.swing.JFrame {

    /**
     * Creates new form N_compra
     */ ConexionSQL cc= new ConexionSQL();
        Connection con = cc.conexion();
        IncAuto au= new IncAuto();
        
        
    public N_producto() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Cantidad = new javax.swing.JLabel();
        Canitdad_actual = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ubicacion = new javax.swing.JTextField();
        No_producto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Validar = new javax.swing.JButton();
        texto2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 360));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 26));

        Nombre.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 211, 26));

        Cantidad.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        Cantidad.setText("Cantidad:");
        getContentPane().add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 60, 25));

        Canitdad_actual.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(Canitdad_actual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 212, 25));

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel4.setText("Ubicacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 30));

        Ubicacion.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(Ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 53, -1));

        No_producto.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        No_producto.addAncestorListener(new javax.swing.event.AncestorListener()
        {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt)
            {
                No_productoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt)
            {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt)
            {
            }
        });
        getContentPane().add(No_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 80, 28));

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel7.setText("Producto Actual N°:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 28));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/Exit.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 32, 28));

        Agregar.setBackground(new java.awt.Color(0, 153, 255));
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/productos.png"))); // NOI18N
        Agregar.setEnabled(false);
        Agregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 70, 70));

        Validar.setBackground(new java.awt.Color(0, 255, 51));
        Validar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/verificar.png"))); // NOI18N
        Validar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ValidarActionPerformed(evt);
            }
        });
        getContentPane().add(Validar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 70, 70));

        texto2.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        texto2.setText("Verificar");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 70, 30));

        texto1.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        texto1.setText("Agregar");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 70, 30));

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel1.setText("Nuevo producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 490, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void No_productoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_No_productoAncestorAdded
        /*esta accion sirve para mostrar al usuario el numero de venta que se está llevando
        principalmente para saber el ID de la Compra en curso*/
        
        No_producto.setText(String.valueOf(au.autoincProducto()));
    }//GEN-LAST:event_No_productoAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OpcionesProductos1 a= new OpcionesProductos1();
        a.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarActionPerformed
        Validar();
    }//GEN-LAST:event_ValidarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        AgregarCompra();
    }//GEN-LAST:event_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void AgregarCompra (){
        /*esta operacion guarda los datos de los campos en el Jframe a la base de datos*/
        String SQL = "insert into productos(id_producto,nombre,cant_inv,ubicacion) values(?,?,?,?)";
        try {
             PreparedStatement pst = con.prepareStatement(SQL);
                pst.setString(1, String.valueOf(au.autoincProducto()));
                pst.setString(2, Nombre.getText());
                pst.setString(3, Canitdad_actual.getText());
                pst.setString(4, Ubicacion.getText());
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(null, "registro exisoto");
                  OpcionesProductos1 a= new OpcionesProductos1();
                  a.setVisible(true);
                  this.dispose();
                  
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog( null,"Error al Guardar"+e.getMessage());
        }
       
        
        
        
    }
    public void Validar(){
        /*esta operacion valida cada uno de los campos para que ningun campo se guarde vacio en 
        la base de datos*/
        
       
            if(!Nombre.getText().isEmpty()){
                if(!Canitdad_actual.getText().isEmpty()){
                    if(!Ubicacion.getText().isEmpty()){
                        Agregar.setEnabled(true);
                        
                    }else{
                        JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           Agregar.setEnabled(false); 
                                           
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           Agregar.setEnabled(false); 
                }
            }else{
                JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           Agregar.setEnabled(false); 
            }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_producto().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField Canitdad_actual;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel No_producto;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Ubicacion;
    private javax.swing.JButton Validar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables


}

