/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import org.omg.CORBA.NO_IMPLEMENT;
import sinvent.ConexionSQL;
import sinvent.IncAuto;

/**
 *
 * @author hp
 */
public class N_Proveedor extends javax.swing.JFrame {

    /**
     * Creates new form N_compra
     */ ConexionSQL cc= new ConexionSQL();
        Connection con = cc.conexion();
        IncAuto au= new IncAuto();
        
        
    public N_Proveedor() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id_producto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        direcc = new javax.swing.JTextField();
        texto = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        Verificar = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 369));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel1.setText("ID Producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 26));

        id_producto.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        id_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_productoActionPerformed(evt);
            }
        });
        getContentPane().add(id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 30));

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, 26));

        nombre.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 250, 30));

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, 31));

        direcc.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(direcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, 30));

        texto.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        texto.setText("Registrar");
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 70, 30));

        telefono.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 160, 30));

        Verificar.setBackground(new java.awt.Color(0, 255, 51));
        Verificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/verificar.png"))); // NOI18N
        Verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarActionPerformed(evt);
            }
        });
        getContentPane().add(Verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 70, 70));

        registrar.setBackground(new java.awt.Color(0, 153, 255));
        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/registrar.png"))); // NOI18N
        registrar.setEnabled(false);
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 70, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/Exit.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 32, 28));

        texto1.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        texto1.setText("Telefono");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 34));

        texto2.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        texto2.setText("Verificar");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 70, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel3.setText("Nuevo Proveedor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sinvent/fondo.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
            agregarProveedor();
    }//GEN-LAST:event_registrarActionPerformed

    private void VerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarActionPerformed
        validar();
    }//GEN-LAST:event_VerificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OpcionesProveedores1 a= new OpcionesProveedores1();
        a.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_productoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_id_productoActionPerformed
    {//GEN-HEADEREND:event_id_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_productoActionPerformed

    /**
     * @param args the command line arguments
     */
    public void agregarProveedor (){
        /*esta operacion guarda los datos de los campos en el Jframe a la base de datos*/
        String SQL = "insert into proveedores(id_proveedor,id_producto,nombre,direcc,telefono) values(?,?,?,?,?)";
        try {
             PreparedStatement pst = con.prepareStatement(SQL);
             
             pst.setString(1, String.valueOf(au.autoincProveedor()));
              pst.setString(2, id_producto.getText());
               pst.setString(3, nombre.getText());
                pst.setString(4, direcc.getText());
                 pst.setString(5, telefono.getText());
                  pst.executeUpdate();
                  JOptionPane.showMessageDialog(null, "registro exisoto");
                  OpcionesProveedores1 a= new OpcionesProveedores1();
                  a.setVisible(true);
                  
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog( null,"Error al Guardar"+e.getMessage());
        }
       
        
        
        
    }
    public void validar(){
        /*esta operacion valida cada uno de los campos para que ningun campo se guarde vacio en 
        la base de datos*/
        
        
            if(!id_producto.getText().isEmpty()){
                if(!nombre.getText().isEmpty()){
                    if(!direcc.getText().isEmpty()){
                        if(!telefono.getText().isEmpty()){
                            registrar.setEnabled(true);
                        }else{
                            JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           registrar.setEnabled(false); 
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           registrar.setEnabled(false); 
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           registrar.setEnabled(false); 
                }
            }else{
                JOptionPane.showMessageDialog(this, "por favor ingrese datos correspondientes ");
                                           registrar.setEnabled(false); 
            }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_Proveedor().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verificar;
    private javax.swing.JTextField direcc;
    private javax.swing.JTextField id_producto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombre;
    public javax.swing.JButton registrar;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    // End of variables declaration//GEN-END:variables


}

